### ISSUE TITLE
Contradiction on the value of P

### ISSUE THREAD

**Issue by nopara73** [lontivero/gcs#6]
@roasbeef [BIP](https://github.com/Roasbeef/bips/blob/master/gcs_light_client.mediawiki) says

> NOTE: P must be a power of two as we target the specialized case of Golomb coding: Golomb-Rice coding.

And you follow it down properly by [asserting](https://github.com/lontivero/gcs/blob/master/src/Filter.cs#L36) it:

```cs
if (P == 0x00 || (P & (P - 1)) != 0)
	throw new ArgumentException("P has to be a power of two value", nameof(P));
``` 

The BIP also says:

> false positive rate MUST be: 20, meaning the parameter P is: 2^20, meaning fp=20.

Which is not a contradiction so far.  

However your implementation doesn't allow this, because P is a byte and its maximum value can be 255. I suspect in your implementation `P` is actually the `fp` and not `P`, therefore you can remove the check.  

The confusion may come from incorrect? `P` in @roasbeef 's reference implementation, which I suspect you based this implementation upon.  

For example [these lines](https://github.com/Roasbeef/btcutil/blob/gcs/gcs/builder/builder.go#L18-L19):

```
// DefaultP is the default collision probability (2^-20)
const DefaultP = 20
```

So it seems like `DefaultP` of the reference implementation is called `fp` in the BIP.  

The commend of the reference implementation is just further confusing. Not only it says `DefaultP` is `(2^-20)` and then defines a constant as `20`, but also where does that `-` sign comes from? The BIP says `2^20`, and not `2^-20`.

**Comment by lontivero** [comment]
The problem is that the `P` parameter is overloaded in the BIP. Let's review it and clarify all this. `fp`  is the `false positive` rate (or the collition probability) that we would accept or expect. This is a rate in the form:

![](https://latex.codecogs.com/gif.latex?fp%20%3D%20%5Cfrac%7B1%7D%7BP%7D)  

Or, as the BIP says:

![](https://latex.codecogs.com/gif.latex?P%20%3D%20%5Cfrac%7B1%7D%7Bfp%7D)

This means that we can calculate the value of `P` given the desired `fp`. We can also calculate the value of `fp` for any given `P`. The point is that we **MUST** to have a `P` value that is power of two (because the implementation requires to work at bit level). Here is were the BIP is not clear enough and start overloading the meaning of `P`. Lets introduce a new `P'` value to make this more clear.

Given `P` **MUST** be power of two, we say that:

![](https://latex.codecogs.com/gif.latex?P%20%3D%202%5E%7BP%27%7D)

Then, replacing it in the calculation fo `fp` we have that:

![](https://latex.codecogs.com/gif.latex?fp%20%3D%20%5Cfrac%7B1%7D%7B2%5E%7BP%27%7D%7D)  

This can also be written as:

![](https://latex.codecogs.com/gif.latex?fp%20%3D%202%5E%7B-P%27%7D)

Note that we have two different values here **P** and **P'**. They are two different values but that is not very clear in the BIP at first glance. Anyway, once we know they are different values, we can understand the code easily. For example, in your fragment of code above, we see:

```
// DefaultP is the default collision probability (2^-20)
const DefaultP = 20
```

`DefaultP` is in fact what I call `P'` and suddenly it become clear that:

![](https://latex.codecogs.com/gif.latex?P%27%20%3D%2020)

Then,

![](https://latex.codecogs.com/gif.latex?fp%20%3D%20%5Cfrac%7B1%7D%7B2%5E%7B20%7D%7D%20%5Ctextrm%7B%20or%20simply%20%7D%20fp%3D2%5E%7B-20%7D) 

So, yes, as the comment says, *collition probability (2^-20)* is  fp=2^-20   

Finally, in our code, everytime we say P (or Default P) we are really refering to the `P'`

**Comment by Roasbeef** [comment]
There is no contradiction. Please refer to the finalized version of the GCS BIP: [BIP 158](https://github.com/bitcoin/bips/blob/master/bip-0158.mediawiki).

**Comment by lontivero** [comment]
The finalized version is much more clear. Thanks @roasbeef

**Comment by nopara73** [comment]
Yes, it's quite unfortunate we were not aware of the finalized version.
