### ISSUE TITLE
Faster BitArray implementation idea

### ISSUE THREAD

**Issue by nopara73** [lontivero/gcs#7]
[This SO answer](https://stackoverflow.com/questions/16471759/is-bitarray-faster-in-c-sharp-for-getting-a-bit-value-than-a-simple-conjuction-w) compares various strategies of working with bits.  

> Testing with 10000000 operations:
> A UInt32 bitfield took 808 ms.
> A BitArray (32) took 574 ms.
> A List<bool>(32) took 436 ms.

You are using the slowest one, that's based on integers. With bools your algo would likely be twice as fast in expense of less efficient space utilization.  

That being said, I am not sure we need to further optimize the speed at this point, since `MatchAny` is quite performant. However if it's easy to replace the implementation or in the future we encounter performance issues, it's worth considering.

**Comment by lontivero** [comment]
In the GCS first version I used the `System.Collections.BitArray` class to perform the bit operations that are required for the Golomb compression algorithm. The performance was so horrible that I decided to run it with a profiler that showed me that the problem that the `System.Collections.BitArray.GetBit()` method was called millons of times.

Basically, the code for reading Ulong values was something like the following:

```c#
// This is pseudo code to ilustrate a problem.
var val = 0UL;
var bitsToRead = 20; // most of the time we read P bits
for(var i=0;i<bitsToRead;i++){
   val |= bitArray[currentPos+i] << i;
}
````

Clearly this is not how we should read multiple bits and there is no way to do it in a different way so, I used ILSpy to review the `System.Collections.BitArray` implementation and I wrote `my own BitArray` class based on the `System.Collections.BitArray`. Both classes use an Int32[] array internally. My BitArray class allows us to read multiples bits with just one call extracting the values from the UInt32 elements throught bitwise operations (no loops). 

After replacing the BitArray class, the `Match` method, the one that reads the compressed set, wasn't a bottleneck any more:

![](https://files.slack.com/files-pri/T34SFJ13J-F96KM444E/image.png?pub_secret=fecc08117b)


Can someone code a faster BitArray implementation in C#? Probably yes, but it won't be an easy task because there are no trivial/obvious points to improve.
